apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-quickstart-messaging
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-gm/manuela-gitops
    targetRevision: HEAD
    path: config/instances/manuela-quickstart/messaging
  destination:
    server: https://kubernetes.default.svc
    namespace: manuela-quickstart-messaging
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
  - group: image.openshift.io
    kind: ImageStream
    jsonPointers:
    - /spec/tags
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
  - group: broker.amq.io
    kind: ActiveMQArtemis
    jsonPointers:
    - /metadata/labels/argocd.argoproj.io/instance
    - /metadata/labels/app.kubernetes.io/instance
